name: Auto-approve

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'aivus'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
